video_size: [1280, 1024]

img_shrink_scale: 4 #用于自瞄的图像相对于源图的缩小比例（减小开销）
# 神经网络相关------------------------------------------------------------------------------------------
small_armor_list : '3x'
#small_armor_list : '3x 4x 5x 8' #不考虑哨兵，所以注释了
#big_armor_list : '1d 3d 4d 5d '
big_armor_list : '1d'

BATCH_SIZE : 10
two_class_trt : "/home/rcclub/python_demo/2Binary_classification.trt"
two_class_txt : '/home/rcclub/python_demo/2_imagenet_classes.txt'
eight_class_trt : "/home/rcclub/python_demo/11Binary_classification.trt"
eight_class_txt : '/home/rcclub/python_demo/11_imagenet_classes.txt'

# 串口参数---------------------------------------------------------------------------------------------
serialPort : "COM3"  # 串口
baudRate : 115200  # 波特率

# 大小装甲板参数 （单位mm）-------------------------------------------------------------------------------
small_obj_points : [[-67., -27.5, 0.],
                    [67., -27.5, 0.],
                    [-67., 27.5, 0.],
                    [67., 27.5, 0.]]

#big_obj_points : [[-112.5, -27.5, 0.],
#                  [112.5, -27.5, 0.],
#                  [-112.5, 27.5, 0.],
#                  [112.5, 27.5, 0.]]

# 内参数矩阵  （？）------------------------------------------------------------------------------------
DAHENG_OldCamera_intrinsic : #大恒

    mtx: [[1.34386883e+03, 0., 1.02702867e+03],
         [0., 1.38920787e+03, 5.62395968e+02],
         [0., 0., 1.]]
    dist: [[-0.13939675, 0.42409417, -0.00454986, 0.01027033, -0.61637364]]



# MDV_BlackCamera_intrinsic :
#
#     mtx: [[1.60954972e+03, 0., 6.36716902e+02],
#                      [0., 1.61293941e+03, 5.27210575e+02],
#                      [0., 0., 1.]]
#     dist: [[-0.08045919, 0.28519144, 0.00188052, -0.00196669, -0.07837469]]



MDV_BlackCamera_intrinsic : #以下这两具体哪个是133哪个是134记不得了

    mtx: [[1.38012881e+03, 0.00000000e+00, 6.32563131e+02],
           [0.00000000e+00, 1.41745621e+03, 3.95972569e+02],
           [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
    dist: [[0.00417728, -0.30223262, -0.01761736, -0.00159902, 1.24798931]]



MDV_WhiteCamera_intrinsic :

    mtx: [[1.61985204e+03, 0.00000000e+00, 6.98384626e+02],
         [0.00000000e+00, 1.65158878e+03, 5.76485699e+02],
         [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
    dist: [[-0.11020907, 0.42616391, -0.00165534, 0.0096811, 0.49850441]]

# 网络推理置信度-----------------------------------------------------------------------------------------
conf_is_it_armor : 0.95 #是否是装甲板的置信度
conf_small_armor : 0.4 #是否是小装甲板的置信度
conf_big_armor : 0.9 #是否是大装甲板的置信度

# 卡尔曼-----------------------------------------------------------------------------------------------
dt : 0.025 #0.025是帧率为40的间隔时间
Q_xyz_scale : 1
Q_vxyz_scale : 1
R_scale : 1    # R_scale越小越相信视觉解算
# 此系数越小表明,越相信"过程",越不相信"观测",就会离pnp解算值越远